name: Test application

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 16.3.0

      - name: Install dependencies
        run: yarn install

      - name: Linting
        run: yarn lint

      - name: Testing
        run: yarn test --coverage

      - name: Upload code coverage
        uses: codecov/codecov-action@v2
        with:
          files: ./coverage/clover.xml
          fail_ci_if_error: true
